//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP_2023MAG.baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Достижения
    {
        public int Номер { get; set; }
        public System.DateTime Дата { get; set; }
        public string Участник { get; set; }
        public string Мероприятие { get; set; }
        public int МестоВЗачете { get; set; }
        public string Статус { get; set; }
        public int КолличествоОчковПрогресса { get; set; }
    }
}
